[book]
title = "The bspwm-wiki"
authors = ["rdbhvr"]
language = "en"

[output.html]
edit-url-template = "https://github.com/rdbhvr-001/bspwm-wiki/edit/main/{path}"
additional-css = ["./assets/css/admonish.css"]


